AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Dada uma fila, obtém todos os clientes (redis) que estão em fila'
Resources:
  getqueueclients:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: 'Dada uma fila, obtém todos os clientes (redis) que estão em fila'
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: '/queue/{id}/client'
            Method: GET
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      VpcConfig:
        SecurityGroupIds:
          -
        SubnetIds:
          -
      Layers:
        - ''
